### ISSUE TITLE
Will-O’-Wisp has `’` which is not recognized in some systems

### ISSUE THREAD

**Issue by zdlovett** [jantoniomartin/monsterurl#1]
The Will-O’-Wisp name has a non-ascii character `’` in the name, which causes issues on some setups. 
Changing the name to instead read `Will-O-Wisp` would help with compatibility, and still be recognizable as everyone favorite spooky ghost light misleading travelers off into the marsh. 

Cheers,
-Z

**Comment by jantoniomartin** [comment]
Fixed, thanks for noticing :smile:

**Comment by zdlovett** [comment]
Thanks for fixing quickly! :-D

**Comment by zdlovett** [comment]
@jantoniomartin Are you planning on pushing another release to pypi with this fix?

**Comment by zdlovett** [comment]
@jantoniomartin any chance for a 0.3 release on pypi with this fix? 😄
